# SPDX-License-Identifier: MIT
# murmur2 - Makefile
#
# Build rules for MurmurHash2 library.

# Library name
lib := murmur2

# Source files
lib-y := src/MurmurHash2.o

# Include paths
includes-y := murmur2/src
