.TH EVIM 1 "2002 February 16"
.SH ИМЯ
evim \- простой uVim, позволяет редактировать файл с помощью uVim в безрежимном режиме
.SH КОМАНДНАЯ СТРОКА
.br
.B evim
[ключи] [файл ..]
.br
.B eview
.SH ОПИСАНИЕ
Команда
.B evim
запускает
.B uVim
и настраивает ряд опций таким образом, что он начинает вести себя
как обычный безрежимный редактор. В этом режиме uVim напоминает
Notepad из MS-Windows.
.B eVim
всегда запускается с поддержкой графического интерфейса, чтобы обеспечить
использование меню и инструментальной панели.
.PP
Эта команда создана для тех, кто по каким-то причинам не в состоянии 
работать с uVim в обычном режиме. Редактирование файлов при этом происходит
гораздо менее эффективно, чем при использовании обычного uVim.
.PP
Команда
.B eview
выполняет почти ту же самую задачу, но файл открывается в режиме "только
для чтения". Использование этой команды полностью идентично использованию 
evim \-R.
.PP
Подробнее о uVim, ключах запуска и т.п. смотрите на странице справочника 
vim(1).
.PP
При использовании
.B evim
включается опция 'insertmode', что позволяет вводить текст напрямую.
.br
Кроме того, настраиваются привязки, позволяющие использовать кнопки MS-Windows
для выполнения команд копирования и вклейки. CTRL-X используется для вырезания 
текста, CTRL-C для копирования и CTRL-V для вклейки. Чтобы воспользоваться
изначальным значением кнопки CTRL-V, используйте CTRL-Q.
.SH ПАРАМЕТРЫ ЗАПУСКА
См. vim(1).
.SH ФАЙЛЫ
.TP 15
/usr/local/lib/vim/evim.vim
Сценарий, который загружается для инициализации eVim.
.SH AKA
eVim также известен как "uVim для чайников".
Для наилучшего эффекта рекомендуется во время использования повязать
на голове платок, предварительно завязав на каждом конце по узелку.
.SH СМОТРИ ТАКЖЕ
vim(1)
.SH АВТОРЫ
Большая часть
.B uVim
создана Брамом Мооленааром (Bram Moolenaar), которому помогает огромное 
количество людей. См. меню Справка/Благодарности.
