function(projt_add_internallibs)
    option(NBT_BUILD_SHARED "Build NBT shared library" OFF)
    option(NBT_USE_ZLIB "Build NBT library with zlib support" ON)
    option(NBT_BUILD_TESTS "Build NBT library tests" OFF)
    projt_push_output_dirs("libnbtplusplus")
    add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../libnbtplusplus libnbtplusplus)
    projt_pop_output_dirs()

    if(NOT LAUNCHER_FUZZ_ONLY)
        projt_push_output_dirs("systeminfo")
        add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../systeminfo systeminfo) # system information library
        projt_pop_output_dirs()
    endif()
    if(NOT LAUNCHER_FUZZ_ONLY)
        projt_push_output_dirs("launcherjava")
        add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../javaloader javaloader) # java based launcher part for Minecraft
        projt_pop_output_dirs()
        projt_push_output_dirs("javacheck")
        add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../javacheck javacheck) # java compatibility checker
        projt_pop_output_dirs()
        projt_push_output_dirs("rainbow")
        add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../rainbow rainbow) # Qt extension for colors
        projt_pop_output_dirs()
        projt_push_output_dirs("LocalPeer")
        add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../LocalPeer LocalPeer) # fork of a library from Qt solutions
        projt_pop_output_dirs()
        if(UNIX AND NOT APPLE)
            if(DEFINED Launcher_BUNDLED_LIBDIR AND NOT Launcher_BUNDLED_LIBDIR STREQUAL "")
                projt_push_install_libdir("${Launcher_BUNDLED_LIBDIR}")
            endif()
            if(DEFINED Launcher_BUNDLED_INCLUDEDIR AND NOT Launcher_BUNDLED_INCLUDEDIR STREQUAL "")
                projt_push_install_includedir("${Launcher_BUNDLED_INCLUDEDIR}")
            endif()
            if(DEFINED Launcher_BUNDLED_LIBEXECDIR AND NOT Launcher_BUNDLED_LIBEXECDIR STREQUAL "")
                projt_push_install_libexecdir("${Launcher_BUNDLED_LIBEXECDIR}")
            endif()
        endif()
        set(GAMEMODE_WITH_PRIVILEGED_GROUP "ptgamemode" CACHE STRING "" FORCE)
        projt_push_output_dirs("gamemode")
        add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../gamemode gamemode)
        projt_pop_output_dirs()
        if(UNIX AND NOT APPLE)
            if(DEFINED Launcher_BUNDLED_LIBEXECDIR AND NOT Launcher_BUNDLED_LIBEXECDIR STREQUAL "")
                projt_pop_install_libexecdir()
            endif()
            if(DEFINED Launcher_BUNDLED_INCLUDEDIR AND NOT Launcher_BUNDLED_INCLUDEDIR STREQUAL "")
                projt_pop_install_includedir()
            endif()
            if(DEFINED Launcher_BUNDLED_LIBDIR AND NOT Launcher_BUNDLED_LIBDIR STREQUAL "")
                projt_pop_install_libdir()
            endif()
        endif()
        projt_push_output_dirs("murmur2")
        add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../murmur2 murmur2) # Hash for usage with the CurseForge API
        projt_pop_output_dirs()
        projt_push_output_dirs("qdcss")
        add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../qdcss qdcss) # css parser
        projt_pop_output_dirs()
    endif()
endfunction()