function(projt_add_minizip)
    set(MINIZIP_BUILD_SHARED ON CACHE BOOL "" FORCE)
    set(MINIZIP_BUILD_STATIC OFF CACHE BOOL "" FORCE)
    set(MINIZIP_BUILD_TESTING OFF CACHE BOOL "" FORCE)
    set(MINIZIP_INSTALL ON CACHE BOOL "" FORCE)
    set(MINIZIP_ENABLE_BZIP2 ON CACHE BOOL "" FORCE)
    if(UNIX AND NOT APPLE)
        if(DEFINED Launcher_BUNDLED_LIBDIR AND NOT Launcher_BUNDLED_LIBDIR STREQUAL "")
            projt_push_install_libdir("${Launcher_BUNDLED_LIBDIR}")
        endif()
        if(DEFINED Launcher_BUNDLED_INCLUDEDIR AND NOT Launcher_BUNDLED_INCLUDEDIR STREQUAL "")
            projt_push_install_includedir("${Launcher_BUNDLED_INCLUDEDIR}")
        endif()
    endif()
    projt_push_output_dirs("minizip")
    add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../ptlibzippy/contrib/minizip minizip)
    projt_pop_output_dirs()
    if(UNIX AND NOT APPLE)
        if(DEFINED Launcher_BUNDLED_INCLUDEDIR AND NOT Launcher_BUNDLED_INCLUDEDIR STREQUAL "")
            projt_pop_install_includedir()
        endif()
        if(DEFINED Launcher_BUNDLED_LIBDIR AND NOT Launcher_BUNDLED_LIBDIR STREQUAL "")
            projt_pop_install_libdir()
        endif()
    endif()
endfunction()