function(projt_add_quazip)
    set(QUAZIP_ENABLE_TESTS OFF CACHE BOOL "" FORCE)
    set(QUAZIP_ENABLE_QTEXTCODEC OFF CACHE BOOL "" FORCE)
    set(QUAZIP_INSTALL ON CACHE BOOL "" FORCE)
    set(QUAZIP_INSTALL_CMAKE_CONFIG OFF CACHE BOOL "" FORCE)
    set(QUAZIP_BZIP2 ON CACHE BOOL "" FORCE)
    set(QUAZIP_FETCH_LIBS OFF CACHE BOOL "" FORCE)
    set(QUAZIP_FORCE_FETCH_LIBS OFF CACHE BOOL "" FORCE)
    # Disable instrumentation for external dependencies to avoid linker issues
    string(REGEX REPLACE "-fprofile-instr-generate|--coverage|-fprofile-generate|-fprofile-arcs|-ftest-coverage" "" CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
    string(REGEX REPLACE "-fprofile-instr-generate|--coverage|-fprofile-generate|-fprofile-arcs|-ftest-coverage" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
    if(UNIX AND NOT APPLE)
        if(DEFINED Launcher_BUNDLED_LIBDIR AND NOT Launcher_BUNDLED_LIBDIR STREQUAL "")
            projt_push_install_libdir("${Launcher_BUNDLED_LIBDIR}")
        endif()
        if(DEFINED Launcher_BUNDLED_INCLUDEDIR AND NOT Launcher_BUNDLED_INCLUDEDIR STREQUAL "")
            projt_push_install_includedir("${Launcher_BUNDLED_INCLUDEDIR}")
        endif()
    endif()
    projt_push_output_dirs("quazip")
    add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../quazip quazip)
    projt_pop_output_dirs()
    if(UNIX AND NOT APPLE)
        if(DEFINED Launcher_BUNDLED_INCLUDEDIR AND NOT Launcher_BUNDLED_INCLUDEDIR STREQUAL "")
            projt_pop_install_includedir()
        endif()
        if(DEFINED Launcher_BUNDLED_LIBDIR AND NOT Launcher_BUNDLED_LIBDIR STREQUAL "")
            projt_pop_install_libdir()
        endif()
    endif()
endfunction()
