name: CI Bzip2

# This workflow is called by ci-new.yml only.
# Do not add push/pull_request triggers here.
on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
      run-bzip2:
        description: 'Whether to run bzip2 jobs'
        required: false
        type: string
        default: 'true'

jobs:
  bzip2-debian-testing-meson:
    if: inputs.run-bzip2 == 'true'
    name: Debian (testing) - Meson
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bzip2
    container:
      image: debian:testing
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Install deps
        run: |
          apt-get update -y
          apt-get install -y gcc meson python3-setuptools python3-pytest valgrind

      - name: Build (meson)
        run: |
          meson builddir
          ninja -C builddir
          meson test -C builddir --print-errorlogs || true

      - name: Collect meson log
        run: |
          cp builddir/meson-logs/meson-log.txt . || true

      - name: Upload meson log
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: bzip2-meson-log-debian-testing
          path: meson-log.txt

  bzip2-debian-testing-cmake-debug:
    if: inputs.run-bzip2 == 'true'
    name: Debian (testing) - CMake Debug
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bzip2
    container:
      image: debian:testing
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Install deps
        run: |
          apt-get update -y
          apt-get install -y gcc make python3-pytest cmake valgrind build-essential libssl-dev qt6-base-dev qt6-base-dev-tools qt6-5compat-dev qt6-networkauth-dev

      - name: Build (cmake debug)
        run: |
          mkdir builddir && cd builddir
          cmake .. -DCMAKE_BUILD_TYPE="Debug" -D ENABLE_SHARED_LIB=ON -D ENABLE_STATIC_LIB=OFF
          cmake --build .
          make check || true

      - name: Collect CMakeOutput.log
        run: |
          cp builddir/CMakeFiles/CMakeOutput.log . || true

      - name: Upload CMakeOutput.log
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: bzip2-CMakeOutput-debian-debug
          path: CMakeOutput.log

  bzip2-debian-testing-cmake:
    if: inputs.run-bzip2 == 'true'
    name: Debian (testing) - CMake
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bzip2
    container:
      image: debian:testing
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Install deps
        run: |
          apt-get update -y
          apt-get install -y gcc make python3-pytest cmake valgrind build-essential libssl-dev qt6-base-dev qt6-base-dev-tools qt6-5compat-dev qt6-networkauth-dev

      - name: Build (cmake)
        run: |
          mkdir builddir && cd builddir
          cmake .. -DCMAKE_BUILD_TYPE="Release" -D ENABLE_SHARED_LIB=ON -D ENABLE_STATIC_LIB=OFF
          cmake --build .
          make check || true

      - name: Collect CMakeOutput.log
        run: |
          cp builddir/CMakeFiles/CMakeOutput.log . || true

      - name: Upload CMakeOutput.log
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: bzip2-CMakeOutput-debian
          path: CMakeOutput.log

  bzip2-debian-testing-cmake-shared-static:
    if: inputs.run-bzip2 == 'true'
    name: Debian (testing) - CMake shared+static
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bzip2
    container:
      image: debian:testing
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Install deps
        run: |
          apt-get update -y
          apt-get install -y gcc make python3-pytest cmake valgrind build-essential

      - name: Build (cmake shared+static)
        run: |
          mkdir builddir && cd builddir
          cmake .. -DCMAKE_BUILD_TYPE="Release" -D ENABLE_SHARED_LIB=ON -D ENABLE_STATIC_LIB=ON
          cmake --build .
          make check || true

      - name: Collect CMakeOutput.log
        run: |
          cp builddir/CMakeFiles/CMakeOutput.log . || true

      - name: Upload CMakeOutput.log
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: bzip2-CMakeOutput-debian-shared-static
          path: CMakeOutput.log

  bzip2-debian-testing-cmake-static-only:
    if: inputs.run-bzip2 == 'true'
    name: Debian (testing) - CMake static only
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bzip2
    container:
      image: debian:testing
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Install deps
        run: |
          apt-get update -y
          apt-get install -y gcc make python3-pytest cmake valgrind libssl-dev

      - name: Build (cmake static)
        run: |
          mkdir builddir && cd builddir
          cmake .. -DCMAKE_BUILD_TYPE="Release" -D ENABLE_SHARED_LIB=OFF -D ENABLE_STATIC_LIB=ON
          cmake --build .
          make check || true

      - name: Collect CMakeOutput.log
        run: |
          cp builddir/CMakeFiles/CMakeOutput.log . || true

      - name: Upload CMakeOutput.log
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: bzip2-CMakeOutput-debian-static
          path: CMakeOutput.log

  bzip2-ubuntu-jammy-meson:
    if: inputs.run-bzip2 == 'true'
    name: Ubuntu Jammy - Meson
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bzip2
    container:
      image: ubuntu:jammy
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Install deps
        run: |
          apt-get update -y
          apt-get install -y gcc python3-pip ninja-build valgrind
          pip3 install meson pytest

      - name: Build (meson)
        run: |
          meson builddir
          ninja -C builddir
          meson test -C builddir --print-errorlogs || true

      - name: Collect meson log
        run: |
          cp builddir/meson-logs/meson-log.txt . || true

      - name: Upload meson log
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: bzip2-meson-log-ubuntu-jammy
          path: meson-log.txt

  bzip2-ubuntu-jammy-cmake:
    if: inputs.run-bzip2 == 'true'
    name: Ubuntu Jammy - CMake
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bzip2
    container:
      image: ubuntu:jammy
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Install deps
        run: |
          apt-get update -y
          apt-get install -y gcc make python3-pip valgrind
          pip3 install --upgrade pip
          pip3 install pytest cmake

      - name: Build (cmake)
        run: |
          mkdir builddir && cd builddir
          cmake .. -DCMAKE_BUILD_TYPE="Release" -D ENABLE_SHARED_LIB=ON -D ENABLE_STATIC_LIB=OFF
          cmake --build .
          make check || true

      - name: Collect CMakeOutput.log
        run: |
          cp builddir/CMakeFiles/CMakeOutput.log . || true

      - name: Upload CMakeOutput.log
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: bzip2-CMakeOutput-ubuntu-jammy
          path: CMakeOutput.log

  bzip2-fedora-meson:
    if: inputs.run-bzip2 == 'true'
    name: Fedora - Meson
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bzip2
    container:
      image: registry.fedoraproject.org/fedora:35
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Install deps
        run: |
          dnf install -y gcc meson python3-pytest valgrind

      - name: Build (meson)
        run: |
          meson builddir
          ninja -C builddir
          meson test -C builddir --print-errorlogs || true

      - name: Collect meson log
        run: |
          cp builddir/meson-logs/meson-log.txt . || true

      - name: Upload meson log
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: bzip2-meson-log-fedora
          path: meson-log.txt

  bzip2-fedora-cmake:
    if: inputs.run-bzip2 == 'true'
    name: Fedora - CMake
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bzip2
    container:
      image: registry.fedoraproject.org/fedora:35
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Install deps
        run: |
          dnf install -y gcc cmake python3-pytest valgrind

      - name: Build (cmake)
        run: |
          mkdir builddir && cd builddir
          cmake .. -DCMAKE_BUILD_TYPE="Release" -D ENABLE_SHARED_LIB=ON -D ENABLE_STATIC_LIB=OFF
          cmake --build .
          make check || true

      - name: Collect CMakeOutput.log
        run: |
          cp builddir/CMakeFiles/CMakeOutput.log . || true

      - name: Upload CMakeOutput.log
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: bzip2-CMakeOutput-fedora
          path: CMakeOutput.log

  bzip2-fedora-rawhide-meson:
    if: inputs.run-bzip2 == 'true'
    name: Fedora Rawhide - Meson
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bzip2
    container:
      image: registry.fedoraproject.org/fedora:rawhide
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Install deps
        run: |
          dnf install -y gcc meson python3-pytest valgrind

      - name: Build (meson)
        run: |
          meson builddir
          ninja -C builddir
          meson test -C builddir --print-errorlogs || true

      - name: Collect meson log
        run: |
          cp builddir/meson-logs/meson-log.txt . || true

      - name: Upload meson log
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: bzip2-meson-log-fedora-rawhide
          path: meson-log.txt

  bzip2-fedora-rawhide-cmake:
    if: inputs.run-bzip2 == 'true'
    name: Fedora Rawhide - CMake
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bzip2
    container:
      image: registry.fedoraproject.org/fedora:rawhide
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Install deps
        run: |
          dnf install -y gcc cmake python3-pytest valgrind

      - name: Build (cmake)
        run: |
          mkdir builddir && cd builddir
          cmake .. -DCMAKE_BUILD_TYPE="Release" -D ENABLE_SHARED_LIB=ON -D ENABLE_STATIC_LIB=OFF
          cmake --build .
          make check || true

      - name: Collect CMakeOutput.log
        run: |
          cp builddir/CMakeFiles/CMakeOutput.log . || true

      - name: Upload CMakeOutput.log
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: bzip2-CMakeOutput-fedora-rawhide
          path: CMakeOutput.log

  bzip2-opensuse-leap-meson:
    if: inputs.run-bzip2 == 'true'
    name: openSUSE Leap - Meson
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bzip2
    container:
      image: opensuse/leap
    steps:
      - name: Install deps
        working-directory: /
        run: |
          zypper install -y git \
             tar \
             gzip \
             ca-certificates \
             gcc \
             gcc-c++ \
             make \
             cmake \
             libopenssl-devel \
             zlib-devel \
             libX11-devel \
             libXcursor-devel \
             libXrandr-devel \
             libXinerama-devel \
             libxkbcommon-devel \
             wayland-devel \
             libdrm-devel \
             Mesa-libEGL-devel \
             Mesa-libGL-devel

      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Install deps
        run: |
          zypper install -y gcc meson ninja python3-pytest valgrind tar

      - name: Build (meson)
        run: |
          meson builddir
          ninja -C builddir
          meson test -C builddir --print-errorlogs || true

      - name: Collect meson log
        run: |
          cp builddir/meson-logs/meson-log.txt . || true

      - name: Upload meson log
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: bzip2-meson-log-opensuse-leap
          path: meson-log.txt

  bzip2-opensuse-leap-cmake:
    if: inputs.run-bzip2 == 'true'
    name: openSUSE Leap - CMake
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bzip2
    container:
      image: opensuse/leap
    steps:
      - name: Install deps
        working-directory: /
        run: |
          zypper install -y git \
             tar \
             gzip \
             ca-certificates \
             gcc \
             gcc-c++ \
             make \
             cmake \
             libopenssl-devel \
             zlib-devel \
             libX11-devel \
             libXcursor-devel \
             libXrandr-devel \
             libXinerama-devel \
             libxkbcommon-devel \
             wayland-devel \
             libdrm-devel \
             Mesa-libEGL-devel \
             Mesa-libGL-devel

      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Install deps
        run: |
          zypper install -y gcc cmake python3-pytest valgrind

      - name: Build (cmake)
        run: |
          mkdir builddir && cd builddir
          cmake .. -DCMAKE_BUILD_TYPE="Release" -D ENABLE_SHARED_LIB=ON -D ENABLE_STATIC_LIB=OFF
          cmake --build .
          make check || true

      - name: Collect CMakeOutput.log
        run: |
          cp builddir/CMakeFiles/CMakeOutput.log . || true

      - name: Upload CMakeOutput.log
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: bzip2-CMakeOutput-opensuse-leap
          path: CMakeOutput.log

  bzip2-opensuse-tumbleweed-meson:
    if: inputs.run-bzip2 == 'true'
    name: openSUSE Tumbleweed - Meson
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bzip2
    container:
      image: opensuse/tumbleweed
    steps:
      - name: Install deps
        working-directory: /
        run: |
          zypper install -y git \
             tar \
             gzip \
             ca-certificates \
             gcc \
             gcc-c++ \
             make \
             cmake \
             libopenssl-devel \
             zlib-devel \
             libX11-devel \
             libXcursor-devel \
             libXrandr-devel \
             libXinerama-devel \
             libxkbcommon-devel \
             wayland-devel \
             libdrm-devel \
             Mesa-libEGL-devel \
             Mesa-libGL-devel

      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Install deps
        run: |
          zypper install -y gcc cmake meson python3-pytest valgrind tar

      - name: Build (meson)
        run: |
          meson builddir
          ninja -C builddir
          meson test -C builddir --print-errorlogs || true

      - name: Collect meson log
        run: |
          cp builddir/meson-logs/meson-log.txt . || true

      - name: Upload meson log
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: bzip2-meson-log-opensuse-tumbleweed
          path: meson-log.txt

  bzip2-opensuse-tumbleweed-cmake:
    if: inputs.run-bzip2 == 'true'
    name: openSUSE Tumbleweed - CMake
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bzip2
    container:
      image: opensuse/tumbleweed
    steps:
      - name: Install deps
        working-directory: /
        run: |
          zypper install -y git \
             tar \
             gzip \
             ca-certificates \
             gcc \
             gcc-c++ \
             make \
             cmake \
             libopenssl-devel \
             zlib-devel \
             libX11-devel \
             libXcursor-devel \
             libXrandr-devel \
             libXinerama-devel \
             libxkbcommon-devel \
             wayland-devel \
             libdrm-devel \
             Mesa-libEGL-devel \
             Mesa-libGL-devel

      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Install deps
        run: |
          zypper install -y gcc cmake python3-pytest valgrind tar

      - name: Build (cmake)
        run: |
          mkdir builddir && cd builddir
          cmake .. -DCMAKE_BUILD_TYPE="Release" -D ENABLE_SHARED_LIB=ON -D ENABLE_STATIC_LIB=OFF
          cmake --build .
          make check || true

      - name: Collect CMakeOutput.log
        run: |
          cp builddir/CMakeFiles/CMakeOutput.log . || true

      - name: Upload CMakeOutput.log
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: bzip2-CMakeOutput-opensuse-tumbleweed
          path: CMakeOutput.log
