name: CI gamemode Build and test

on:
  push:
    paths:
      - 'gamemode/**'
      - '.github/workflows/ci-build-and-test-gamemode.yml'
  pull_request:
    paths:
      - 'gamemode/**'
      - '.github/workflows/ci-build-and-test-gamemode.yml'
  workflow_call:
    inputs:
      ref:
        description: Ref to build
        required: false
        type: string
  workflow_dispatch:
    inputs:
      ref:
        description: Ref to build
        required: false
        type: string
permissions:
  contents: read
  actions: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gamemode
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref || github.event.inputs.ref || github.sha }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential meson appstream clang clang-format clang-tools libdbus-1-dev libinih-dev libsystemd-dev systemd-dev
      - name: Check format
        env:
          CI: "true"
        run: |
          ./scripts/format-check.sh
      - name: Build and install
        env:
          CI: "true"
        run: |
          ./bootstrap.sh -Dwith-examples=true
      - name: Tests
        run: |
          meson test -C builddir
      - name: Simulate game
        run: |
          dbus-run-session -- gamemode-simulate-game
      - name: Static analyser check
        run: |
          ./scripts/static-analyser-check.sh
      - name: Upload logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: gamemode-logs
          path: |
            gamemode/builddir/meson-logs/
