name: CI libqrencode build

on:
  push:
    paths:
      - 'libqrencode/**'
      - '.github/workflows/ci-configure-qren.yml'
  pull_request:
    paths:
      - 'libqrencode/**'
      - '.github/workflows/ci-configure-qren.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    defaults:
      run:
        working-directory: libqrencode

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit
    - uses: actions/checkout@v6
    - name: brew setup
      if: matrix.os == 'macos-latest'
      run: brew install automake autoconf libtool pkg-config libpng
    - name: generate configure script
      run: ./autogen.sh
    - name: configure
      run: ./configure --with-tests
    - name: make
      run: make -j 2
    - name: make check
      run: make check
    - name: make distcheck
      run: make -j 2 distcheck
