name: Linting libpng

on:
  push:
    paths:
      - 'libpng/**'
      - 'ptlibzippy/**'
      - '.github/workflows/ci-lint-libpng.yml'
  pull_request:
    paths:
      - 'libpng/**'
      - 'ptlibzippy/**'
      - '.github/workflows/ci-lint-libpng.yml'
  workflow_call:
    inputs:
      ref:
        description: Ref to lint
        required: false
        type: string
  workflow_dispatch:
    inputs:
      ref:
        description: Ref to lint
        required: false
        type: string

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.event.inputs.ref || github.sha }}
      - name: Install lint dependencies
        shell: bash
        run: |
          set -euxo pipefail
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends python3-pip shellcheck
          python3 -m pip install --user yamllint
      - name: Install editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@main
      - name: Run the linting script
        working-directory: libpng
        run: bash ./ci/ci_lint.sh
        shell: bash
        env:
          CI_YAMLLINT: /home/runner/.local/bin/yamllint
