name: Python Atheris Fuzz

on:
  schedule:
    - cron: "0 5 * * 2"
  workflow_dispatch:
  push:
    paths:
      - "meta/fuzz/**"
      - "meta/requirements.txt"
      - ".github/workflows/ci-meta-python-fuzz.yml"
  pull_request:
    paths:
      - "meta/fuzz/**"
      - "meta/requirements.txt"
      - ".github/workflows/ci-meta-python-fuzz.yml"

permissions:
  contents: read

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r meta/requirements.txt atheris
      - name: Run Atheris
        run: |
          python meta/fuzz/meta/fuzz_meta_models.py -runs=2000
