name: mingw/cygwin

on:
  push:
    paths:
      - 'ptlibzippy/**'
      - '.github/workflows/ci-ptlibzippy-msys-cygwin.yml'
  pull_request:
    paths:
      - 'ptlibzippy/**'
      - '.github/workflows/ci-ptlibzippy-msys-cygwin.yml'
  workflow_dispatch:

jobs:
  MSys:
    runs-on: ${{ matrix.os || 'windows-latest' }}
    strategy:
      fail-fast: false
      matrix:
        sys: [mingw32, mingw64, ucrt64, clang64, clangarm64]
        include:
          - sys: clangarm64
            os: windows-11-arm
    name: MSys - ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: >-
          make
        pacboy: >-
          toolchain:p
          cmake:p
    - name: Configure
      if: matrix.sys != 'clang64'
      working-directory: ptlibzippy
      run: |
        src_dir="."
        build_dir="build"
        cmake -G"Unix Makefiles" \
          -S "$src_dir" \
          -B "$build_dir" \
          -DCMAKE_VERBOSE_MAKEFILE=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DPTLIBZIPPY_BUILD_MINIZIP=ON \
          -DMINIZIP_ENABLE_BZIP2=ON
    - name: Configure clang64
      if: matrix.sys == 'clang64'
      working-directory: ptlibzippy
      run: |
        src_dir="."
        build_dir="build"
        CC=clang cmake -G"Unix Makefiles" \
          -S "$src_dir" \
          -B "$build_dir" \
          -DCMAKE_VERBOSE_MAKEFILE=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DPTLIBZIPPY_BUILD_MINIZIP=ON \
          -DMINIZIP_ENABLE_BZIP2=ON
    - name: Build
      working-directory: ptlibzippy
      run: cmake --build build --config Release
    - name: Run tests
      working-directory: ptlibzippy
      run: ctest --output-on-failure --test-dir build -C Release

  cygwin:
    strategy:
      fail-fast: false
    runs-on: windows-latest
    name: Cygwin
    defaults:
      run:
        shell: C:\cygwin\bin\bash.exe --login -lc "{0}"

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          packages: >-
            cmake
            cygwin-devel
            gcc-core
            gcc-g++
            ninja

      - name: Add Cygwin to PATH
        run: echo "C:\cygwin\bin" >> $GITHUB_PATH

      - name: Configure
        run: |
          cd ptlibzippy
          src_dir="."
          build_dir="build"

          cmake -S "$src_dir" \
            -B "$build_dir" \
            -DCMAKE_BUILD_TYPE=Release \
            -DPTLIBZIPPY_BUILD_MINIZIP=ON \
            -DMINIZIP_ENABLE_BZIP2=OFF \
            -G Ninja

      - name: Build
        run: |
          cd ptlibzippy
          cmake --build build --config Release -v -j1

      - name: Run tests
        run: |
          cd ptlibzippy
          ctest --output-on-failure --test-dir build -C Release
