name: CI Scheduled Jobs

# This workflow is called by ci-new.yml only.
# Do not add push/pull_request triggers here.
on:
  workflow_call:
    inputs:
      schedule-cron:
        required: true
        type: string
      is-pr-closed:
        required: true
        type: string
      is-release:
        required: true
        type: string
    secrets:
      ORG_MEMBERS_TOKEN:
        required: false
      TOKEN:
        required: false
      WINGET_TOKEN:
        required: false

jobs:
  update-flake:
    if: github.repository_owner == 'Project-Tick'
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git line endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false

      - name: Normalize line endings
        run: |
          git add --renormalize .
          git reset --hard HEAD

      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15

      - name: Use PAT
        run: echo "GITHUB_TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV

      - uses: DeterminateSystems/update-flake-lock@5adeaaaf36f64df54f62adb34aa5fbfdb0109d34
        with:
          commit-msg: "chore(nix): update lockfile"
          pr-title: "chore(nix): update lockfile"
          pr-labels: |
            41.changelog:omit

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@23c09f60046c64f1b0079b44af614bfa411395b9
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
