name: Winget Release
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git reference to build from
        required: false
        default: main
        type: string
      tag_name:
        description: Tag name of the release
        required: true
        type: string
  workflow_call:
    inputs:
      ref:
        description: Git reference to build from
        required: true
        default: main
        type: string
      tag_name:
        description: Tag name of the release
        required: true
        type: string

jobs:
  winget:
    name: Winget
    runs-on: windows-latest
    steps:
      - name: Publish on Winget
        uses: vedantmgoyal2009/winget-releaser@19e706d4c9121098010096f9c495a70a7518b30f
        with:
          identifier: ProjectTick.ProjTLauncher
          version: ${{ inputs.tag_name }}
          installers-regex: 'ProjTLauncher-Windows-MSVC(:?-arm64|-Legacy)?-Setup-.+\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
