name: Verifying libpng on Linux

on:
  workflow_call:
    inputs:
      ref:
        description: Ref to verify
        required: false
        type: string
  workflow_dispatch:
    inputs:
      ref:
        description: Ref to verify
        required: false
        type: string

permissions:
  contents: read

jobs:
  verify-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.event.inputs.ref || github.sha }}
      - name: Install dependencies
        shell: bash
        run: |
          set -euxo pipefail
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends autoconf automake build-essential libtool m4 zlib1g-dev
      - name: Run the configure verification script
        working-directory: libpng
        run: bash ./ci/ci_verify_configure.sh
        env:
          CI_MAKE_FLAGS: -j2
          CI_SANITIZERS: address,undefined
